import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="flex gap-4 px-4 py-2">
          <Link href="/">Unoptimized</Link>
          <Link href="/next-image">next/image</Link>
          <Link href="/optimized">Optimized</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
